# Generated by Django 4.0 on 2022-01-03 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='card_id',
            new_name='card',
        ),
        migrations.AlterField(
            model_name='card',
            name='cnp',
            field=models.CharField(
                max_length=13,
                validators=[django.core.validators.RegexValidator(
                    code='nomatch',
                    message='CNP-ul trebuie sa aiba lungimea '
                    '13si sa fie format din cifre.',
                    regex='^[0-9]{13}$')]
                ),
        ),
    ]
